version: '3'
services:
  btc-explorer:
    build: btc-explorer/.
    ports:
      - "8888:3002"
    environment:
      - BTCEXP_BITCOIND_HOST=miner-node
      - BTCEXP_BITCOIND_PORT=18443
      - BTCEXP_BITCOIND_USER=user
      - BTCEXP_BITCOIND_PASS=password
    networks:
      - internal

  miner-node:
    build: btc/.
    ports:
      - "18400:18443"
      - "18500:18444"
    expose: 
      - "18443"
      - "18444"
    command: ["-addnode=hot-node:18444", "-addnode=cold-node:18444"]
    volumes:
      - "./btc/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro"
      - "./btc/miner:/root/.bitcoin/miner:rw"
    networks:
      - internal

  hot-node:
    build: btc/.
    ports:
      - "18402:18443"
      - "18502:18444"
    expose:
      - "18444"
    command: ["-addnode=miner-node:18444", "-addnode=cold-node:18444"]
    volumes:
      - "./btc/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro"
      - "./btc/hot:/root/.bitcoin/hot:rw"
    networks:
      - internal

  cold-node:
    build: btc/.
    ports:
      - "18403:18443"
      - "18503:18444"
    expose: 
      - "18444"
    command: ["-addnode=miner-node:18444", "-addnode=hot-node:18444"]
    volumes:
      - "./btc/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro"
      - "./btc/cold:/root/.bitcoin/cold:rw"
    networks:
      - internal

  faucet:
    build: faucet/.
    ports:
      - "8333:8080"
    volumes:
      - ${PWD}/faucet/config.json:/src/config.json
    networks:
      - internal

  notificator:
    build:
      context: notificator/.
    image: pg-notificator
    ports:
      - "12380:80"
    environment:
      NSQ_URI: "nsqd:4150"
      NSQ_TOPIC: "cryptogate-btc-blockchain-events"
    networks:
      - internal
      - processing_processing

networks:
  internal:
  processing_processing:
    external: true