version: '3'
services:
  btc-explorer:
    build: btc-explorer/.
    ports:
      - "8888:3002"
    environment:
      - BTCEXP_BITCOIND_HOST=miner-node
      - BTCEXP_BITCOIND_PORT=18443
      - BTCEXP_BITCOIND_USER=user
      - BTCEXP_BITCOIND_PASS=password
  miner-node:
    build: btc/.
    ports:
      - "18400:18443"
      - "18500:18444"
    expose: 
      - "18443"
      - "18444"
    command: ["-addnode=hot-node:18444", "-addnode=cold-node:18444"]
    volumes:
      - "./btc/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro"
      - "./btc/miner:/root/.bitcoin/miner:rw"
  hot-node:
    build: btc/.
    ports:
      - "18402:18443"
      - "18502:18444"
    expose:
      - "18444"
    command: ["-addnode=miner-node:18444", "-addnode=cold-node:18444"]
    volumes:
      - "./btc/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro"
      - "./btc/hot:/root/.bitcoin/hot:rw"
  cold-node:
    build: btc/.
    ports:
      - "18403:18443"
      - "18503:18444"
    expose: 
      - "18444"
    command: ["-addnode=miner-node:18444", "-addnode=hot-node:18444"]
    volumes:
      - "./btc/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro"
      - "./btc/cold:/root/.bitcoin/cold:rw"
  faucet:
    build: faucet/.
    ports:
      - "8333:8080"
