version: '3'
services:
  btc-explorer:
    build: explorer/.
    environment:
      - BTCEXP_BITCOIND_HOST=btc-miner-node
      - BTCEXP_BITCOIND_PORT=18443
      - BTCEXP_BITCOIND_USER=user
      - BTCEXP_BITCOIND_PASS=password
      - PORT=80
    networks:
      - internal

  btc-miner-node:
    build: nodes/btc/.
    ports:
      - "18400:18443"
      - "18500:18444"
    expose: 
      - "18443"
      - "18444"
    command: ["-addnode=btc-hot-node:18444", "-addnode=btc-cold-node:18444"]
    volumes:
      - "./nodes/btc/miner:/root/.bitcoin:rw"
      - "./nodes/btc/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro"
    networks:
      - internal

  btc-hot-node:
    build: nodes/btc/.
    ports:
      - "18402:18443"
      - "18502:18444"
    expose:
      - "18444"
    command: ["-addnode=btc-miner-node:18444", "-addnode=btc-cold-node:18444"]
    volumes:
      - "./nodes/btc/hot:/root/.bitcoin:rw"
      - "./nodes/btc/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro"
    networks:
      - internal

  btc-cold-node:
    build: nodes/btc/.
    ports:
      - "18403:18443"
      - "18503:18444"
    expose: 
      - "18444"
    command: ["-addnode=btc-miner-node:18444", "-addnode=btc-hot-node:18444"]
    volumes:
      - "./nodes/btc/cold:/root/.bitcoin:rw"
      - "./nodes/btc/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro"
    networks:
      - internal

  btc-faucet:
    build: faucet/.
    volumes:
      - ${PWD}/faucet/btc-config.json:/app/config.json
    networks:
      - internal

networks:
  internal: