version: '3'
services:
  btc-explorer:
    build: btc-explorer/.
    ports:
      - "8888:3002"
    environment:
      - BTCEXP_BITCOIND_HOST=btc-miner-node
      - BTCEXP_BITCOIND_PORT=18443
      - BTCEXP_BITCOIND_USER=user
      - BTCEXP_BITCOIND_PASS=password
    networks:
      - internal

#  doge-explorer:
#    build: btc-explorer/.
#    ports:
#      - "8889:3002"
#    environment:
#      - BTCEXP_BITCOIND_HOST=doge-miner-node
#      - BTCEXP_BITCOIND_PORT=18443
#      - BTCEXP_BITCOIND_USER=user
#      - BTCEXP_BITCOIND_PASS=password
#    networks:
#      - internal

  btc-miner-node:
    build: btc/.
    ports:
      - "18400:18443"
      - "18500:18444"
    expose: 
      - "18443"
      - "18444"
    command: ["-addnode=btc-hot-node:18444", "-addnode=btc-cold-node:18444"]
    volumes:
      - "./btc/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro"
      - "./btc/miner:/root/.bitcoin/miner:rw"
    networks:
      - internal

  btc-hot-node:
    build: btc/.
    ports:
      - "18402:18443"
      - "18502:18444"
    expose:
      - "18444"
    command: ["-addnode=btc-miner-node:18444", "-addnode=btc-cold-node:18444"]
    volumes:
      - "./btc/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro"
      - "./btc/hot:/root/.bitcoin/hot:rw"
    networks:
      - internal

  btc-cold-node:
    build: btc/.
    ports:
      - "18403:18443"
      - "18503:18444"
    expose: 
      - "18444"
    command: ["-addnode=btc-miner-node:18444", "-addnode=btc-hot-node:18444"]
    volumes:
      - "./btc/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro"
      - "./btc/cold:/root/.bitcoin/cold:rw"
    networks:
      - internal

  doge-miner-node:
    build: doge/.
    ports:
      - "18410:18443"
      - "18510:18444"
    expose:
      - "18443"
      - "18444"
    command: ["-addnode=doge-hot-node:18444", "-addnode=doge-cold-node:18444"]
    volumes:
      - "./doge/dogecoin.conf:/root/.dogecoin/dogecoin.conf:ro"
      - "./doge/miner:/root/.dogecoin/miner:rw"
    networks:
      - internal

  doge-hot-node:
    build: doge/.
    ports:
      - "18412:18443"
      - "18512:18444"
    expose:
      - "18444"
    command: ["-addnode=doge-miner-node:18444", "-addnode=doge-cold-node:18444"]
    volumes:
      - "./doge/dogecoin.conf:/root/.dogecoin/dogecoin.conf:ro"
      - "./doge/hot:/root/.dogecoin/hot:rw"
    networks:
      - internal

  doge-cold-node:
    build: doge/.
    ports:
      - "18413:18443"
      - "18513:18444"
    expose:
      - "18444"
    command: ["-addnode=doge-miner-node:18444", "-addnode=doge-hot-node:18444"]
    volumes:
      - "./doge/dogecoin.conf:/root/.dogecoin/dogecoin.conf:ro"
      - "./btc/cold:/root/.dogecoin/cold:rw"
    networks:
      - internal

  btc-faucet:
    build: faucet/.
    ports:
      - "8333:8080"
    volumes:
      - ${PWD}/faucet/btc-config.json:/app/config.json
    networks:
      - internal

  doge-faucet:
    build: faucet/.
    ports:
      - "8334:8080"
    volumes:
      - ${PWD}/faucet/doge-config.json:/app/config.json
    networks:
      - internal

networks:
  internal: